---
title: "testing"
output: html_document
---

# ```{r setup, include=FALSE}
# knitr::opts_chunk$set(echo = TRUE)
# ```

```{r}
# strain_data <- read_tsv(strains) %>% 
#   mutate(Date     = as.Date(paste(Year, Month, Day, sep = "-")),
#          Location = paste(Country, Province, City, sep = "_"))
# strain_data <- strain_data[1:15000,]
  
source_pw <- read_tsv(source_file) %>% mutate(Source.Dist = 1- value) %>% select(-value)
  
date_assignments <- strain_data %>% select("Date")
  
dim(date_assignments)
  
dm <- distMatrix(date_assignments, "temp", "Date")

x <- benchmark(
  "reshape2_melt" = {
    meltedDM <- dm %>% as.data.frame() %>% reshape2::melt(., measure.vars = colnames(.))}, 
  "datatable_melt" = {
    meltedDM <- dm %>% as.data.table() %>% data.table::melt.data.table(., measure.vars = colnames(.))}, 
  replications = 3, 
  columns = c("test", "replications", "elapsed", "user.self", "sys.self"))

# On a set of 7000 strains:
#             test replications elapsed user.self sys.self
# 2 datatable_melt            3   50.88     41.69     3.91
# 1  reshape2_melt            3   56.75     45.60     7.17

# On a set of 10000 strains:
#             test replications elapsed user.self sys.self
# 2 datatable_melt            3  120.33     95.60    14.93
# 1  reshape2_melt            3  136.91    107.65    13.00

# On a set of 12000 strains:
#             test replications elapsed user.self sys.self
# 2 datatable_melt            3  189.12    135.67    39.51
# 1  reshape2_melt            3  192.56    139.66    32.65
```

Inner join versus left join
```{r}
y <- benchmark(
  "inner_join_call" = {
    dm4 <- strains_sc %>% inner_join(., dm3, by = c("SC" = "SC1")) %>% 
      rename(SC1 = SC, Strain.1 = Strain) %>% 
      inner_join(strains_sc, ., by = c("SC" = "SC2")) %>% 
      rename(SC2 = SC, Strain.2 = Strain) %>% 
      select(Strain.1, Strain.2, Temp.Dist)
  }, 
  "left_join_call" = {
    dm4 <- strains_sc %>% left_join(., dm3, by = c("SC" = "SC1")) %>% 
      rename(SC1 = SC, Strain.1 = Strain) %>% 
      left_join(strains_sc, ., by = c("SC" = "SC2")) %>% 
      rename(SC2 = SC, Strain.2 = Strain) %>% 
      select(Strain.1, Strain.2, Temp.Dist)
  }, 
  replications = 10, 
  columns = c("test", "replications", "elapsed", "user.self", "sys.self")
)

# results, on a set using 6000 strains:
#              test replications elapsed user.self sys.self
# 1 inner_join_call           10   15.53     11.67     2.86
# 2  left_join_call           10   14.99     11.50     2.37
```

Collecting ECCs with pairwise duplicates pared down before analysis, or not
```{r}
source("tmp.R")
library(rbenchmark)
source("dist_sections.R")
library(pryr)
z <- benchmark(
  "original" = {
    oneCombo(params$strains, params$source, c1$sigma, c1$tau, c1$gamma, params$cpus, td)
  }, 
  "new_method" = {
    newECCS(params$strains, params$source, c1$sigma, c1$tau, c1$gamma, params$cpus, td)
  }, 
  replications = 4, 
  columns = c("test", "replications", "elapsed", "user.self", "sys.self")
)
#           test replications elapsed user.self sys.self
# 2   new_method            4  257.01    235.58    20.84
# 1     original            4  745.86    710.53    30.46

# then, with assignments minimized by type
#         test replications elapsed user.self sys.self
# 2 new_method            4  236.27    218.13    15.67
# 1   original            4  744.55    697.72    36.90
```

Testing sampled clusters - using new method and original
```{r}
source("dist_sections.R")
library(rbenchmark)
z <- benchmark(
  "original" = {
    actualResults()
  }, 
  "new_method" = {
    testResults()
  }, 
  replications = 4, 
  columns = c("test", "replications", "elapsed", "user.self", "sys.self")
)
```

```{r}
a <- actualResults()
saveRDS(a, "allTP2T0_actual.Rds")

b <- testResults()
saveRDS(b, "allTP2T0_test.Rds")
```


```{r}
a <- readRDS("allTP2T0_actual.Rds") %>% as.data.table()
a$T0_ECC[is.na(a$T0_ECC)] <- 1

b <- readRDS("allTP2T0_test.Rds") %>% as.data.table()
b$T0_ECC[is.na(b$T0_ECC)] <- 1

all(abs(a$T0_ECC - b$T0_ECC) < 1e-10)
```

Cluster sampling tests
Testing
```{r, message=FALSE}
source("basicinputs.R")
source("scripts/ECC/ecc_functions.R")
source("scripts/ECC/epi-helper-modular.R")
source("scripts/ECC/epi-helper.R")
source("scripts/ECC/ECC-sep_singletons.R")
source("dist_sections.R")

checkColumns <- function(x, y, tol) {
  first_col <- identical(pull(x, 1), pull(y, 1))
  second_col <- identical(pull(x, 2), pull(y, 2))

  a <- pull(x, 3)
  b <- pull(y, 3)
  third_col <- all(abs((a-b)) < tol)
    
  return(all(first_col, second_col, third_col))
}
```

```{r}
raw_strains <- read_tsv(params$strains) %>% 
    mutate(Date     = as.Date(paste(Year, Month, Day, sep = "-")), 
           Location = paste(Country, Province, City, sep = "_"))

source_pw <- read_tsv(params$source) %>% mutate(Source.Dist = 1- value) %>% select(-value)

td <- tp1$height_list %>% append(tp2$height_list)
assert("Only one threshold in processed typing data", ncol(td[[2]]) == 1)
tol <- 1e-14

for (it in 1:50) {
  td <- tp1$height_list %>% append(tp2$height_list)
  
  incl_clusters <- datasetSizeBelow(td, 1500)
  
  incl_clusters %>% sort() %>% print()
  c2name <- colnames(td[[2]])
  td[[2]] <- td[[2]] %>% filter(!!as.symbol(c2name) %in% incl_clusters)
  td[[1]] <- td[[1]] %>% filter(rownames(td[[1]]) %in% rownames(td[[2]]))

  strain_data <- raw_strains %>% filter(Strain %in% rownames(td[[2]]))

  # typing_datum <- td[[2]]
  case1a <- actualResults(source_pw, strain_data, c1$sigma, tau, gamma, typing_datum = td[[2]]) %>% 
    as_tibble() %>% set_colnames(c("Th", "Th_Size", "Th_ECC")) %>% 
    mutate(Th_ECC = ifelse(is.na(Th_ECC), 1, Th_ECC))
  
  case1b <- testResults(strain_data, tau, gamma, typing_datum = td[[2]]) %>% 
    set_colnames(c("Th", "Th_Size", "Th_ECC")) %>% mutate(Th_ECC = ifelse(is.na(Th_ECC), 1, Th_ECC))

  
  print(paste0("Iteration ", it, ": "))
  assert(paste0("Test results and original results are the same, within a tolerance of ", tol), 
         checkColumns(case1a, case1b, tol))
}

```


